fetch_news_task:
  description: "Fetch news articles based on the given topic."
  expected_output: "A dictionary of news articles."
  tools: [fetch_news]
  agent: trend_analyzer

analyze_trends_task:
  description: "Analyze collected news articles to identify trends, determine age groups, and assess popularity scores."
  expected_output: "A list of identified trends with age groups and popularity scores."
  tools: [analyze_trends]
  agent: trend_analyzer

write_blog_post_task:
  description: "Write a blog post based on identified trends. Include age groups, popularity scores, and other relevant details."
  expected_output: "A blog post formatted in markdown."
  tools: [save_blog_post]
  agent: blog_writer
